CREATE TABLE IF NOT EXISTS `TERC` (
	WOJ CHAR(2),
	POW CHAR(2),
	GMI CHAR(2),
	RODZ TINYINT,
	NAZWA VARCHAR(36),
	NAZDOD VARCHAR(50),
	STAN_NA DATE
) charset="utf8";

CREATE TABLE IF NOT EXISTS `ULIC` (
	WOJ CHAR(2),
	POW CHAR(2),
	GMI CHAR(2),
	RODZ_GMI TINYINT,
	SYM CHAR(7),
	SYM_UL CHAR(5),
	CECHA CHAR(5),
	NAZWA_1 VARCHAR(100),
	NAZWA_2 VARCHAR(100),
	STAN_NA DATE
) charset="utf8";

CREATE TABLE IF NOT EXISTS `SIMC` (
	WOJ CHAR(2),
	POW CHAR(2),
	GMI CHAR(2),
	RODZ_GMI TINYINT,
	RM CHAR(2),
	MZ ENUM('tak', 'nie'),
	NAZWA VARCHAR(56),
	SYM CHAR(7),
	SYMPOD CHAR(7),
	STAN_NA DATE
) charset="utf8";


CREATE TABLE IF NOT EXISTS `WMRODZ` (
	RM CHAR(2),
	NAZWA_RM CHAR(24),
	STAN_NA DATE
) charset="utf8";

